# Generated by Django 5.1 on 2025-10-13 02:20

import apps.core.dbfields
import django.core.validators
import django.db.models.expressions
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="amount",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.expressions.CombinedExpression(
                    models.F("debit"), "-", models.F("credit")
                ),
                output_field=apps.core.dbfields.MoneyField(
                    decimal_places=4,
                    max_digits=24,
                    validators=[
                        django.core.validators.MinValueValidator(
                            0, message="Value must be greater than or equal to 0"
                        )
                    ],
                ),
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True, verbose_name="uuid"
            ),
        ),
    ]
