# Generated by Django 5.1 on 2025-11-05 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0002_transaction_amount_alter_transaction_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('date',), 'permissions': (('view_deleted_transactions', 'Can view deleted transactions'),), 'verbose_name': 'transaction', 'verbose_name_plural': 'transactions'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=10, validators=[django.core.validators.RegexValidator('^09\\d{8}$', "mobile number's pattern must be like 0933222111")], verbose_name='mobile'),
        ),
    ]
